name: ZMK Build
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
    with:
      config-path: config
      build-file: config/build.yaml
      cmake-args: -DZEPHYR_EXTRA_MODULES=$GITHUB_WORKSPACE/firmware/zmk-keyboard-knaeckebrot
    secrets: inherit
