name: Main Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
    with:
      # The path to your config folder.
      config-path: config
      # The name of the build-file in your config folder.
      build-file: build.yaml
    secrets: inherit