name: Build

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: zmkfirmware/zmk-build-arm:3.5
    strategy:
      matrix:
        include:
          - board: nice_nano_v2
            shield: knaeckebrot_left
            artifact-name: knaeckebrot_left-nice_nano_v2-zmk
          - board: nice_nano_v2
            shield: knaeckebrot_right
            artifact-name: knaeckebrot_right-nice_nano_v2-zmk
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Initialize workspace
        run: west init -l .
      - name: Update west dependencies
        run: west update
      - name: Find ZMK app directory
        run: find . -name "app" -type d | grep zmk
      - name: Build ${{ matrix.shield }} for ${{ matrix.board }}
        run: west build -s $(find . -path "*/zmk/app" | head -1) -b ${{ matrix.board }} -- -DSHIELD=${{ matrix.shield }} -DZMK_CONFIG="$(pwd)/config"
      - name: Archive firmware
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact-name }}
          path: build/zephyr/zmk.uf2
