name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: zmkfirmware/zmk-build-arm:3.5
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Initialize workspace
        run: west init -l .
      - name: Update west dependencies
        run: west update
      - name: Build Firmwares
        run: west build -s zmk/app -b nice_nano_v2 -- -DSHIELD=knaeckebrot_left -DZMK_CONFIG="config"
      - name: Archive firmware
        uses: actions/upload-artifact@v3
        with:
          name: firmware
          path: build/zephyr/zmk.uf2
